"""Константы для приложения."""

MAX_HISTORY_MESSAGES = 10

VECTOR_SEARCH_LIMIT = 50
DEFAULT_VECTOR_SEARCH_K = 10

DEFAULT_SQL_LIMIT = 50
MAX_SQL_LIMIT = 100

DEFAULT_TEMPERATURE = 0.7
TEXT_TO_SQL_TEMPERATURE = 0.1

MAX_AGENT_ITERATIONS = 15
MAX_AGENT_EXECUTION_TIME = 60

MAX_SQL_RETRY_ATTEMPTS = 3

EMBEDDING_DELAY_SECONDS = 0.1
EMBEDDING_BATCH_SIZE = 10

HTTP_TIMEOUT_SECONDS = 10.0
DB_CONNECTION_TIMEOUT = 10.0
DB_COMMAND_TIMEOUT = 30.0

# Опасные SQL операции, которые запрещены
# Проверяется только наличие этих ключевых слов - все остальное разрешено
DANGEROUS_SQL_KEYWORDS = [
    "DROP",
    "TRUNCATE",
    "DELETE",
    "INSERT",
    "EXECUTE",
    "EXEC",
    # Также запрещаем UPDATE и ALTER для безопасности
    "UPDATE",
    "ALTER",
    "CREATE",
]
