"""Константы для работы с базой данных."""

TABLE_CONVERSATION_HISTORY = "conversation_history"
TABLE_AGENT_CONTEXT = "agent_context"
TABLE_PROMPTS = "prompts"
TABLE_SYSTEM = "system"
TABLE_RULES = "rules"
TABLE_ORDERS = "orders"
TABLE_PRODUCTS = "products"
TABLE_PRICE_HISTORY = "price_history"

COLUMN_CLIENT_PHONE = "client_phone"
COLUMN_ROLE = "role"
COLUMN_MESSAGE = "message"
COLUMN_CONTEXT_DATA = "context_data"
COLUMN_TOPIC = "topic"
COLUMN_PROMPT = "prompt"
COLUMN_VALUE = "value"
COLUMN_RULE_NAME = "rule_name"
COLUMN_RULE_TYPE = "rule_type"
COLUMN_RULE_VALUE = "rule_value"
COLUMN_CATEGORY = "category"
COLUMN_CREATED_AT = "created_at"
COLUMN_TITLE = "title"
COLUMN_DESTINATION = "destination"
COLUMN_PRICE_OUT = "price_out"
COLUMN_WEIGHT_KG = "weight_kg"

SCHEMA_MYASO = "myaso"

