"""Константы для ретриверов."""

VECTOR_SEARCH_LIMIT = 50
DEFAULT_VECTOR_SEARCH_K = 10

ENABLE_QUERY_REWRITING = False
ENABLE_RERANKING = False
CONTEXT_CACHE_TTL_SECONDS = 300
MAX_HISTORY_FOR_REWRITING = 10

EMBEDDING_DELAY_SECONDS = 0.1
EMBEDDING_BATCH_SIZE = 10
